config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :providers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/provider.rb
class Provider < ApplicationRecord

  validates :first_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :last_name, presence:true
  validates :price, presence:true
  validates :category, presence:true
  validates :expertise, presence:true
  validates :rating, numericality: { lower_than_or_equal_to: 5}
  validates :phone, uniqueness:true, length: { is: 10 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]


  def index
      @providers = Provider.all
      @last_db_update =  Provider.order("created_at").last.updated_at.to_formatted_s(:short)
  end

  def show
  end

  def new
    @provider = Provider.new

  end

  def create
    @provider = Provider.new(product_params)
    if @provider.save
      redirect_to providers_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @provider.update(product_params)
      redirect_to provider_path
    else
      render :edit
    end
  end

  def destroy
    @provider.destroy
    redirect_to providers_path
  end

  private

  def product_params
    params.require(:provider).permit(:last_name, :first_name, :email,
      :price, :rating, :category, :expertise, :phone)
  end

  def find_product
    @provider = Provider.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://unsplash.it/1280/720?random');">
  <div class="banner-content">
    <h1>Anagram.paris</h1>
    <p>Base de donnée Freelance</p>
    <%= link_to "voir la liste", providers_path, class:" btn btn-primary" %>
  </div>
</div>

app/views/providers/_form.html.erb
<%= simple_form_for(@provider) do |f| %>
  <%= f.error_notification %>
  <%= f.input :category, :collection => %w[Développeur SEO Intégrateur SEM], label: "Catégorie" %>
  <%= f.input :expertise, :collection => %w[Wordpress Symphonie Node Rails],label: "Expertise" %>
  <%= f.input :first_name, placeholder: "Alex", label: "Prénom" %>
  <%= f.input :last_name, placeholder: "Roubinet", label: "Nom" %>
  <%= f.input :email, placeholder: "alex@anagram.paris", label: "Email" %>
  <%= f.input :phone, placeholder: "06 ...", label: "Téléphone" %>
  <%= f.input :price, placeholder: "100", label: "Tarif jour" %>
  <%= f.input :rating, input_html: { min:0, max:5} %>
  <%= f.button :submit, "Ajouter", class: "btn btn-success" %>
  <%= link_to 'Retour', providers_path, class: "btn btn-primary" %>

<% end %>

app/views/providers/edit.html.erb
<h1>Editing Provider</h1>

<%= render 'form', provider: @provider %>

<div>
  <ul>
    <li><%= link_to 'Annuler', @provider, class: "btn btn-danger" %></li>
    <li><%= link_to 'Retour', providers_path, class: "btn btn-warning" %></li>
  </ul>
</div>

app/views/providers/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="text-center">Répertoire de freelance</h2>
<h4 class="text-center"><%= @providers.length %> freelances dans la base de donnée </h4>

    <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Catégorie</th>
                  <th>Expertise</th>
                  <th>Prénom</th>
                  <th>Nom</th>
                  <th>Email</th>
                  <th>Téléphone</th>
                  <th>Prix</th>
                  <th>Note</th>
                </tr>
              </thead>
              <tbody>
                  <% @providers.each do |provider| %>
                  <tr>
                    <th><%= provider.category %></th>
                     <th><%= provider.expertise %></th>
                    <th><%= link_to provider.first_name, provider_path(provider) %></th>
                    <th><%= link_to provider.last_name, provider_path(provider)  %></th>
                    <th><%= provider.email %></th>
                    <th><%= provider.phone %></th>
                    <th><%= provider.price %></th>
                    <th><%= provider.rating %></th>
                  </tr>
                  <% end %>
              </tbody>
            </table>
          </div>
<div class="container">
  <p class="text-center">Dernière maj : <%= @last_db_update %></p>
</div>

app/views/providers/new.html.erb
<div class="container">
<h1 class="text-center">Ajout d'un freelance</h1>
    <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= render 'form', provider: @provider %>
    </div>
  </div>
</div>

app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= @provider.category %></p>
<p><%= @provider.expertise %></p>
<p><%= @provider.first_name %></p>
<p><%= @provider.last_name %></p>
<p><%= @provider.email%></p>
<p><%= @provider.phone%></p>
<p><%= @provider.price%></p>
<p><%= @provider.rating%></p>


<%= link_to 'Editer', edit_provider_path(@provider) %> |
<%= link_to 'Retour', providers_path %>
<%= link_to 'Détruire', provider_path(@provider) , method: :delete, data: { confirm: 'Êtes-vous certains ?' } %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Text link -->
    <%= link_to "Répertoire", providers_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Button (call-to-action) -->
    <%= link_to "Ajouter un prestataire", new_provider_path, class: "navbar-wagon-item navbar-wagon-button btn" %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="http://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>